all:
  vars:
    ansible_user: alice
    ansible_ssh_private_key_file: ~/.ssh/alice.pem
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    host1.example.com:
    host2.example.com:
    host3.example.com:
